# @format

version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "14:00"
    cooldown:
      default-days: 3
    commit-message:
      prefix: "chore"
      include: "scope"
    assignees:
      - "lumikeiju"
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "14:00"
    cooldown:
      default-days: 3
    commit-message:
      prefix: "chore"
      include: "scope"
    assignees:
      - "lumikeiju"
